/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Pizza(props) {
  // The path should be relative to the root when using the `public` folder in Next.js
  const { nodes, materials } = useGLTF('/scene/pizza.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Pepperoni}
        position={[0.605, 0.09, -0.392]}
        rotation={[-0.054, 0.307, 1.57]}
        scale={[0.042, 0.105, 0.105]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.Greens}
        position={[0.742, 0.1, -0.076]}
        scale={0.017}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SurfPatch.geometry}
        material={materials.Bacon}
        position={[0.46, 0.168, -0.061]}
        rotation={[-0.079, 0.309, 0.282]}
        scale={[-0.009, -0.082, -0.068]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_1.geometry}
        material={materials.PizzaBase}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_2.geometry}
        material={materials.Cheese}
      />
    </group>
  );
}

// Preload the GLTF model
useGLTF.preload('/scene/pizza.gltf');
